[build]
    command = "hugo && hugulp build"
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.38.2"

[context.production.environment]
    HUGO_ENV = "production"
    NODE_ENV = "production"
