---
upload_path: "/static/images/uploads/"
frontmatter_file_url_template: "/images/uploads/"
body_file_url_template: "/images/uploads/post-uploads/"
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: ''
sections: 
version: 0.38.1
