---
upload_path: "/static/images/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/images/uploads/:year:/:month:/:day:"
body_file_url_template: "/images/uploads/post/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: ''
sections: 
version: 0.38.1
