---
hide_body: false
is_partial: false
fields:
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: []
- name: featureimage
  label: Featureimage
  type: text
  hidden: false
  default: ''
  description: This will also be used as OG Image for Facebook/Twitter Cards.
- name: menu
  label: Menu
  type: text
  hidden: true
  default: ''
